# Generated by Django 6.1.1 on 2026-10-07 16:46

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
